import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <body className=" bg-gradient-to-br from-[#09070f] from-50% to-[#071920]">
          {children}
        </body>
      </head>
    </html>
  )
}
